=== openscriptures/HebrewLexicon/HebrewLexicon.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://www.APTBibleTools.com/namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.APTBibleTools.com/namespace" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	
	<xs:annotation>
		<xs:documentation>
			<p>The HebrewLexicon schema is version 1.1.
			It is released to the public domain.</p>
		</xs:documentation>
	</xs:annotation>
	
	<xs:element name="lexicon" type="lexiconCT"/>
	
	<!-- complex types -->
	
	<xs:complexType name="lexiconCT">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="entry" type="entryCT"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="entryCT">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="w" type="wCT"/>
			<xs:element name="note" type="xs:string"/>
			<xs:element name="source" type="sourceCT"/>
			<xs:element name="meaning" type="sourceCT"/>
			<xs:element name="usage" type="sourceCT"/>
			<xs:element name="bdb" type="bdbCT"/>
			<xs:element name="xref" type="xrefCT"/>
			<xs:element name="status" type="statusCT"/>
		</xs:choice>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="wCT">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="pos" type="xs:string"/>
				<xs:attribute name="pron" type="xs:string"/>
				<xs:attribute name="xlit" type="xs:string"/>
				<xs:attribute ref="xml:lang"/>
				<xs:attribute name="src" type="xs:IDREF"/>
				<xs:attribute name="origin" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="sourceCT" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="w" type="wCT"/>
			<xs:element name="note" type="xs:string"/>
			<xs:element name="def" type="xs:string"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="bdbCT" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="w" type="wCT"/>
			<xs:element name="pos" type="xs:string"/>
			<xs:element name="stem" type="xs:string"/>
			<xs:element name="asp" type="xs:string"/>
			<xs:element name="def" type="xs:string"/>
			<xs:element name="em" type="xs:string"/>
			<xs:element name="sense" type="senseCT"/>
		</xs:choice>
		<xs:attribute name="type" type="entryType" default="entry"/>
		<xs:attribute name="cite" type="citationType" default="partial"/>
		<xs:attribute name="form" type="xs:boolean" default="true"/>
		<xs:attribute name="mod" type="modList"/>
	</xs:complexType>
	
	<xs:complexType name="xrefCT">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="twot" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="statusCT">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="p" type="xs:integer"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="senseCT" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="pos" type="xs:string"/>
			<xs:element name="stem" type="xs:string"/>
			<xs:element name="asp" type="xs:string"/>
			<xs:element name="def" type="xs:string"/>
			<xs:element name="em" type="xs:string"/>
			<xs:element name="sense" type="senseCT"/>
			<xs:element name="w" type="wCT"/>
		</xs:choice>
		<xs:attribute name="n" type="xs:string"/>
	</xs:complexType>
	
	<!-- simple types -->
	
	<xs:simpleType name="entryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="root"/>
			<xs:enumeration value="entry"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="citationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="full"/>
			<xs:enumeration value="partial"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="modList">
		<xs:list itemType="modType"/>
	</xs:simpleType>
	
	<xs:simpleType name="modType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[IVXLCDM]+"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== openscriptures/HebrewLexicon/HebrewMeshRoots.xml
<?xml version="1.0" encoding="utf-8"?>
<lexicon xsi:schemaLocation="http://www.APTBibleTools.com/namespace HebrewLexicon.xsd" 
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			 xmlns="http://www.APTBibleTools.com/namespace">
	<entry id="a1">
		<w xlit="aleph" xml:lang="heb">×</w>
		<bdb><w>×</w> <def>Ä€leph</def>, first letter; in post B Heb.=numeral 1 (and so in margin of printed MT); <w>×Ö¿</w> = 1000; no evidence of this usage in OT times.</bdb>
		<status p="1">done</status>
	</entry>
	<entry id="abb">
		<bdb><w>××‘×‘</w> (<def>fresh</def>, <def>bright</def>, As. <foreign xml:lang="akk">abÃ¢bu</foreign> Dlw, AGl.)</bdb>
		<xref twot="1"/>
		<status p="1">done</status>
	</entry>
	<entry id="abe2">
	  <bdb mod="II"><w>××‘×”</w> (perh. at least formally justified as stem of <w>×Ö¸×‘</w> (cstr. <w>×Ö²×‘Ö´×™</w>), so Thea (cf. infr.), but existence &amp; mng. wholly dub.; as real &#x221A; Ba ZMG 1887. 609 ff. Ol Â§123c; acc . to DlW p. 22 <w>××‘×”</w> As. <foreign xml:lang="akk">abÃ»</foreign> =
	    <def>decide</def>, <w>×Ö¸×‘</w> = <def>he who decides</def>; Thes (so RobGes NÃ¶ ZMGxl,737 &amp; cf. Sta Â§186 al.) makes <w>×Ö¸×‘</w> nom. prim. bilit., imitating infant's speech cf. <foreign xml:lang="grc">Ï€Î¬Ï€Ï€Î±Ï‚</foreign>, pappa,
papa (cf. EWI Â§106a); also As. <foreign xml:lang="akk">bab</foreign> Jen ZAI886.404).</bdb>
		<xref twot="4"/>
		<status p="3">done</status>
	</entry>
	<entry id="abl2">
	  <bdb mod="II"><w>××‘×œ</w> (perh.<foreign xml:lang="ara">Arabic</foreign> <def>grow green</def>, cf. <foreign xml:lang="syr">Syriac</foreign> <def>grass</def> Lag BN45 prop. <foreign xml:lang="ara">Arabic</foreign> <def>withstand</def>, hence <foreign xml:lang="he">×Ö¸×‘Öµ×œ</foreign> as withstanding scorching sun (protected by trees, springs, etc.), hence also (Lag) <foreign xml:lang="ara">Arabic</foreign> <def>camel</def>).</bdb>
		<xref twot="7"/>
		<status p="5">base</status>
	</entry>
	<entry id="abl4">
	  <bdb mod="III"><w>××‘×œ</w> (cf. Ar. <foreign xml:lang="ara">Arabic</foreign> <def>able to manage camels</def>, fr. <foreign xml:lang="ara">Arabic</foreign>, coll., Sab. ××‘×œ <def>camel</def> DHM ZMG 1883, 329).</bdb>
		<status p="6">base</status>
	</entry>
	<entry id="abr">
		<bdb><w>××‘×¥</w> (meaning unknown).</bdb>
		<status p="7">done</status>
	</entry>
	<entry id="abs">
		<bdb><w>××‘×§</w> (Ar. <foreign xml:lang="ara">Arabic</foreign> <def>run away</def> (cf. Lag BN51)).</bdb>
		<xref twot="11"/>
		<status p="7">base</status>
	</entry>
	<entry id="abt">
	  <bdb><w>××‘×¨</w> (cf. As. <foreign xml:lang="akk">abÃ¢ru</foreign>, <def>be firm, strong</def> DlW)</bdb>
		<xref twot="13"/>
		<status p="7">done</status>
	</entry>
	<entry id="aca">
	  <bdb><w>××’×</w> (cf. Ar. <foreign xml:lang="ara">Arabic</foreign>, <def>flee</def> Frey).</bdb>
		<status p="8">base</status>
	</entry>
	<entry id="acd">
	  <bdb><w>××’×“</w> (<def>bind</def>, so Talm. <w>×Ö¸×’Ö·×“</w>, Aram. <foreign xml:lang="arc">×Ö²×’Ö·×“</foreign>).</bdb>
		<xref twot="15"/>
		<status p="8">done</status>
	</entry>
	<entry id="acl">
	  <bdb><w>××’×œ</w> (Hoffm Hiob. 86 compo Ar. <foreign xml:lang="ara">Arabic</foreign> <def>restrict</def>, Eth. <foreign xml:lang="gez">Ethiopic</foreign> <def>a certain one</def> (name <def>withheld</def>), etc.)</bdb>
		<xref twot="17"/>
		<status p="8">base</status>
	</entry>
	<entry id="acm">
	  <bdb><w>××’×</w> (<def>troubled, sad</def>, As. <foreign xml:lang="akk">agÃ¢mu</foreign> DlW cf. Ar.
	    <foreign xml:lang="ara">Arabic</foreign> <def>loathe</def>; also <foreign xml:lang="ara">Arabic</foreign> <def>marshy jungle</def> v. <w>×¢×’×</w>).</bdb>
		<xref twot="18"/>
		<status p="8">base</status>
	</entry>
	<entry id="acn">
	  <bdb><w>××’×Ÿ</w> (prob. <def>circular, round</def>, cf. Ar. <foreign xml:lang="ara">Arabic</foreign> <def>ball</def> of <def>cheek</def> &amp; v. Talm. <w>××•Ö¹×’Ö¶×Ÿ</w> <def>curved rim of a vessel</def>).</bdb>
		<xref twot="20"/>
		<status p="8">base</status>
	</entry>
	<entry id="acq">
	  <bdb><w>××’×£</w> (As. stem of <foreign xml:lang="akk">agappu</foreign>, <def>wing</def>, cf. DlW).</bdb>
		<xref twot="21"/>
		<status p="8">done</status>
	</entry>
	<entry id="act2">
	  <bdb mod="II"><w>××’×¨</w> (<def>pay, hire</def>, Ar. <foreign xml:lang="ara">Arabic</foreign>, Aram. <w>×Ö²×’Ö·×¨</w>, <foreign xml:lang="ara">Arabic</foreign>, As. <foreign xml:lang="akk">agÃ¢ru</foreign> DlW, Palm. <w>×¢×’×¨</w> Reck ZMG 1888, 396).</bdb>
		<xref twot="23"/>
		<status p="8">base</status>
	</entry>
	<entry id="add">
	  <bdb><w>××“×“</w> (? cf. Ar. <foreign xml:lang="ara">Arabic</foreign> <def>strength</def>).</bdb>
		<status p="9">done</status>
	</entry>
	<entry id="adm1">
	  <bdb mod="I"><w>××“×</w> (cf. As. [<foreign xml:lang="akk">adÃ¢mu</foreign>] <def>make, produce</def> (?) Dlw W. &amp; Pr 104).</bdb>
		<xref twot="25"/>
		<status p="9">done</status>
	</entry>
	<entry id="adm2">
	  <bdb mod="II"><w>××“×</w> (<foreign xml:lang="ara">Arabic</foreign>, <foreign xml:lang="ara">Arabic</foreign> <def>tawny</def>, Eth. <foreign xml:lang="gez">Ethiopic</foreign> (only in derivatives), As. <foreign xml:lang="akk">adÃ¢mu</foreign> ? DlW; cf. Lag BN28).</bdb>
		<xref twot="26"/>
		<status p="10">base</status>
	</entry>
	<entry id="adn">
	  <bdb><w>××“×Ÿ</w> (mng. disputed; (1) cf. As. [<foreign xml:lang="akk">adannu</foreign>] <def>firm, strong</def>; adv. <foreign xml:lang="akk">adanniÅ¡</foreign>, <def>strongly, exceedingly</def> DlW > (2) FÃ¼. (a) <def>make firm, fasten</def> (cf. <foreign xml:lang="ara">Arabic</foreign>) whence <w>×Ö¶×“Ö¶×Ÿ</w>; (b) <def>determine, command, rule</def>, whence <w>×Ö¸×“×•Ö¹×Ÿ</w>; (3) Thes Add., MV al. (a) intr. <def>be under, low, inferior</def> (cf. <w>×“Ö¼×•Ö¼×Ÿ</w>, <foreign xml:lang="ara">Arabic</foreign>), whence <w>×Ö¶×“Ö¶×Ÿ</w>; (b) tr. <def>put under command, rule over</def> (cf. <w>×“Ö¼Ö´×™×Ÿ</w>) whence <w>×Ö¸×“×•Ö¹×Ÿ</w>; v. also (4) Lag M.i. 102, <w>×Ö¸×“×•Ö¹×Ÿ</w> fro. <foreign xml:lang="ara">Arabic</foreign>).</bdb>
		<xref twot="27"/>
		<status p="10">base</status>
	</entry>
	<entry id="aed">
		<bdb><w>××”×“</w> (= <w>××—×“</w>? v. Thes.)</bdb>
		<status p="13">done</status>
	</entry>
	<entry id="ael1">
	  <bdb mod="I"><w>××”×œ</w> (<def>settle down</def> (?), Ar. <foreign xml:lang="ara">Arabic</foreign> <def>be inhabited</def>, cf. As. <foreign xml:lang="akk">Ã¢lu</foreign>, <def>settlement, city</def>, <foreign xml:lang="akk">maÊ¾Ã¢lu</foreign>, <foreign xml:lang="akk">maÊ¾Ã¢ltu</foreign>, <def>bed</def>; DlW &amp; Pr 105).</bdb>
		<status p="13">base</status>
	</entry>
	<entry id="afb">
	  <bdb><w>××•×‘</w> (meaning? Thes. comp. Ar. <foreign xml:lang="ara">Arabic</foreign> <def>return</def>, <foreign xml:lang="ara">Arabic</foreign> <def>water-carrier</def>; but cf. LagBN90). MV comp. <w>××‘×‘</w> (with conjectural sense) to get meaning <def>have a hollow sound</def>. Deriv. and signif. totally uncertain). </bdb>
		<xref twot="37"/>
		<status p="15">base</status>
	</entry>
	<entry id="afd">
	  <bdb><w>××•×“</w> (<def>be curved, bent</def>, also trans. <def>burden, oppress</def>, cf. Ar. <foreign xml:lang="ara">Arabic</foreign>) 1).</bdb>
		<xref twot="38"/>
		<status p="15">base</status>
	</entry>
	<entry id="afe1">
	  <bdb mod="I"><w>××•×”</w> 1. Ar. <foreign xml:lang="ara">Arabic</foreign> <def>betake oneself</def> to a place for dwelling, etc.; 2. id., <def>be tenderly inclined</def>.</bdb>
		<xref twot="39"/>
		<status p="15">base</status>
	</entry>
	<entry id="afj">
	  <bdb mod="III"><w>××•×”</w> (<def>to cry</def> <w>×Ö¹×•×™</w>, <def>howl</def> cf. Ar. <foreign xml:lang="ara">Arabic</foreign>, <def>to cry</def> <foreign xml:lang="ara">Arabic</foreign> to be assumed prob. as source of two foIl. words).</bdb>
		<xref twot="43"/>
		<status p="17">base</status>
	</entry>
	<entry id="afl1">
	  <bdb mod="I"><w>××•×œ</w> (<def>be foolish</def>, cf. <w>×™××œ</w> Ar. <foreign xml:lang="ara">Arabic</foreign> <def>grow thick</def> (of fluids)).</bdb>
		<xref twot="44"/>
		<status p="17">base</status>
	</entry>
	<entry id="afl2">
	  <bdb mod="II"><w>××•×œ</w>, <w>××™×œ</w> (<def>be in front of, precede, lead</def>; v.Thes NÃ¶MBA 1880. 774; 8BA 18c2 1175, who comp. Ar. <foreign xml:lang="ara">Arabic</foreign> for <foreign xml:lang="ara">Arabic</foreign>, Targ. <w>××•×•×œ×</w>; cf. Sab. <w>××•×œ</w> DHM Epigr. Denkm.33.34; v. on the other hand LagOr ii. p. 3;
	    M i. p. 100 &amp; sub I. <w>××œ×”</w> infr.)</bdb>
		<xref twot="45"/>
		<status p="17">base</status>
	</entry>
	<entry id="afn1">
	  <bdb><w>××•×Ÿ</w> (cf. Ar. <foreign xml:lang="ara">Arabic</foreign> (med. <foreign xml:lang="ara">Arabic</foreign>) <def>be fatigued, tired</def>,
	    <foreign xml:lang="ara">Arabic</foreign>, <def>weariness, sorrow, trouble</def>).</bdb>
		<xref twot="48"/>
		<status p="19">base</status>
	</entry>
	<entry id="afn2">
	  <bdb mod="II"><w>××•×Ÿ</w> (cf. Ar. <foreign xml:lang="ara">Arabic</foreign> (med. <foreign xml:lang="ara">Arabic</foreign>) <def>be at rest, at ease, enjoy life of plenty</def>; <foreign xml:lang="ara">Arabic</foreign> <def>one enjoying a life of ease, freedom from toil &amp; trouble</def>).</bdb>
		<xref twot="49"/>
		<status p="20">base</status>
	</entry>
	<entry id="agn1">
	  <bdb mod="I"><w>××–×Ÿ</w> (<def>pointed, sharp</def>? cf. Eth. <foreign xml:lang="gez">Ethiopic</foreign> <def>edge, corner, peak, pinnacle</def>; v. also As. DlW, &amp; <w>×Ö¸×–Öµ×Ÿ</w> infr.)</bdb>
		<status p="23">base</status>
	</entry>
	<entry id="ahe1">
	  <bdb><w>××—×”</w> (stem assumed for <w>×Ö¸×—</w>; which however perh. bilit. &amp; prim. so Thes Rob Ges al.; DlHA 59 prop. <def>surround, protect</def>; DlW comp. <foreign xml:lang="akk">aá¸«u</foreign>, <def>side</def>. Zehnpfnnd BAS I. 510 prop. <def>belong together</def>, cf. Schult. Thes. De Goeje in RSSem 256 N suggests connection with <foreign xml:lang="akk">á¸¥ayy</foreign>, <def>family, clan</def>).</bdb>
		<xref twot="62"/>
		<status p="26">done</status>
	</entry>
